// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SPHealthSupportSystem_Repositories.Models;

public partial class PsychologyTheory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int TopicId { get; set; }

    public string Author { get; set; }

    public int? YearPublished { get; set; }

    public string TheoryType { get; set; }

    public string Principle { get; set; }

    public string Application { get; set; }

    public string RelatedTheory { get; set; }

    public string Criticism { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual Topic Topic { get; set; }
}