// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SPHealthSupportSystem_Repositories.Models;

public partial class StudentInfo
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? Grade { get; set; }

    public string Group { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<StudentHealth> StudentHealths { get; set; } = new List<StudentHealth>();
}