// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SPHealthSupportSystem_Repositories.Models;

public partial class StudentHealth
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int StudentInfoId { get; set; }

    public int? SurveyId { get; set; }

    public int? LastSurveyResultId { get; set; }

    public int? CurrentProgramId { get; set; }

    public int? AppointmentId { get; set; }

    public int? DashboardInfoId { get; set; }

    public string MentalHealthCategory { get; set; }

    public int? RiskLevel { get; set; }

    public int? SurveyHistoryCount { get; set; }

    public int? ProgramParticipation { get; set; }

    public int? AppointmentHistory { get; set; }

    public DateTime LastUpdated { get; set; }

    public string Notes { get; set; }

    public virtual StudentInfo StudentInfo { get; set; }
}