// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SPHealthSupportSystem_Repositories.Models;

public partial class Topic
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<PsychologyTheory> PsychologyTheories { get; set; } = new List<PsychologyTheory>();
}